# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], default='Hombre', max_length=140)),
                ('especialidad', models.CharField(choices=[('endodoncia', 'Endodoncia'), ('odontopediatria', 'Odontopediatría'), ('ortodoncia', 'Ortodoncia'), ('periodoncia', 'Periodoncia'), ('Implantologia', 'Periodoncia'), ('prot-bucal', 'Prótesis Bucal'), ('prot-maxilofacial', 'Prótesis Maxilofacial'), ('salud-publica', 'Salud Pública Bucal'), ('materiales-detales', 'Materiales Dentales'), ('patoliga-bucal', 'Patologia Bucal')], default='Ortodoncia', max_length=140)),
                ('telefono', models.IntegerField()),
                ('foto', models.ImageField(upload_to='fotomedico')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
