# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160910_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
