# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('time', models.TimeField()),
                ('nom_paciente', models.TextField()),
                ('apellido_paciente', models.TextField()),
                ('edad', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('correo', models.TextField()),
                ('issue', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='accounts.Medico')),
            ],
        ),
    ]
