# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('appellidos', models.CharField(max_length=140)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], default='Hombre', max_length=140)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotopaciente')),
            ],
        ),
    ]
