# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='apellido_paciente',
        ),
        migrations.AddField(
            model_name='consulta',
            name='apellido_materno',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='apellido_paterno',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
