# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('appellidos', models.CharField(max_length=140)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], default='Hombre', max_length=140)),
                ('especialidad', models.CharField(choices=[('endodoncia', 'Endodoncia'), ('odontopediatria', 'Odontopediatría'), ('ortodoncia', 'Ortodoncia'), ('periodoncia', 'Periodoncia'), ('Implantologia', 'Periodoncia'), ('prot-bucal', 'Prótesis Bucal'), ('prot-maxilofacial', 'Prótesis Maxilofacial'), ('salud-publica', 'Salud Pública Bucal'), ('materiales-detales', 'Materiales Dentales'), ('patoliga-bucal', 'Patologia Bucal')], default='Ortodoncia', max_length=140)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotomedico')),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='foto',
        ),
    ]
