# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_auto_20160910_1907'),
        ('consultas', '0003_auto_20160910_1906'),
    ]

    operations = [
    ]
